baseurl = "https://nanx.me/hugo-tanka/"
title = "Hugo Tanka Theme"
author = "Nan Xiao"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Ecclesia Sanctorum"

[[menu.main]]
    name = "Domus"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Bibla"
    url = "/bibla/"
    weight = 2
[[menu.main]]
    name = "Missa"
    url = "/missa/"
    weight = 3
[[menu.main]]
    name = "Doctrina"
    url = "/doctrina/"
    weight = 4
[[menu.main]]
    name = "Auctore"
    url = "/auctore/"
    weight = 5
